/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.transversal.Vistas;

/**
 *
 * @author Agente Sosa
 */
public class MenuPrincipal extends javax.swing.JFrame {

    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMAlumno = new javax.swing.JMenu();
        FormAlum = new javax.swing.JMenuItem();
        jMMateria = new javax.swing.JMenu();
        FormMate = new javax.swing.JMenuItem();
        jMAdministracion = new javax.swing.JMenu();
        ManeInscri = new javax.swing.JMenuItem();
        ManeNota = new javax.swing.JMenuItem();
        jMConsultas = new javax.swing.JMenu();
        AlumxMate = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        jMAlumno.setText("Alumno");
        jMAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAlumnoActionPerformed(evt);
            }
        });

        FormAlum.setText("Formulario de Alumno");
        FormAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormAlumActionPerformed(evt);
            }
        });
        jMAlumno.add(FormAlum);

        jMenuBar1.add(jMAlumno);

        jMMateria.setText("Materia");

        FormMate.setText("Formulario de Materia");
        FormMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormMateActionPerformed(evt);
            }
        });
        jMMateria.add(FormMate);

        jMenuBar1.add(jMMateria);

        jMAdministracion.setText("Administacion");

        ManeInscri.setText("Manejo de Inscripciones");
        ManeInscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManeInscriActionPerformed(evt);
            }
        });
        jMAdministracion.add(ManeInscri);

        ManeNota.setText("Manipulacion de Notas");
        ManeNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManeNotaActionPerformed(evt);
            }
        });
        jMAdministracion.add(ManeNota);

        jMenuBar1.add(jMAdministracion);

        jMConsultas.setText("Consultas");

        AlumxMate.setText("Alumnos por Materia");
        AlumxMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlumxMateActionPerformed(evt);
            }
        });
        jMConsultas.add(AlumxMate);

        jMenuBar1.add(jMConsultas);

        jMSalir.setText("Salir");
        jMSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMSalirMouseClicked(evt);
            }
        });
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FormAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormAlumActionPerformed
        // TODO add your handling code here:
        
        Escritorio.removeAll();
        Escritorio.repaint();
        FormularioAlumno verventana = new FormularioAlumno(); 
        Escritorio.add(verventana);
        verventana.show(); 
        Escritorio.moveToFront(verventana);
        
    }//GEN-LAST:event_FormAlumActionPerformed

    private void jMAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAlumnoActionPerformed
        // TODO add your handling code here:   
    }//GEN-LAST:event_jMAlumnoActionPerformed

    private void ManeInscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManeInscriActionPerformed
        // TODO add your handling code here:
        
        Escritorio.removeAll();
        Escritorio.repaint();
        ManejoInscripciones verventana = new ManejoInscripciones();
        Escritorio.add(verventana);
        verventana.show();
        Escritorio.moveToFront(verventana);
        
    }//GEN-LAST:event_ManeInscriActionPerformed

    private void FormMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormMateActionPerformed
        // TODO add your handling code here:
        
        Escritorio.removeAll();
        Escritorio.repaint();
        FormularioMateria verventana = new FormularioMateria(); 
        Escritorio.add(verventana);
        verventana.show();
        Escritorio.moveToFront(verventana);
        
    }//GEN-LAST:event_FormMateActionPerformed

    private void ManeNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManeNotaActionPerformed
        // TODO add your handling code here:
        
        Escritorio.removeAll();
        Escritorio.repaint();
        ManejoNotas verventana = new ManejoNotas();
        Escritorio.add(verventana);
        verventana.show();
        Escritorio.moveToFront(verventana);
        
    }//GEN-LAST:event_ManeNotaActionPerformed

    private void AlumxMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlumxMateActionPerformed
        // TODO add your handling code here:
        
        Escritorio.removeAll();
        Escritorio.repaint();
        AlumnosxMateria verventana = new AlumnosxMateria();
        Escritorio.add(verventana);
        verventana.show(); 
        Escritorio.moveToFront(verventana);
        
    }//GEN-LAST:event_AlumxMateActionPerformed

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMSalirActionPerformed

    private void jMSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_jMSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AlumxMate;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem FormAlum;
    private javax.swing.JMenuItem FormMate;
    private javax.swing.JMenuItem ManeInscri;
    private javax.swing.JMenuItem ManeNota;
    private javax.swing.JMenu jMAdministracion;
    private javax.swing.JMenu jMAlumno;
    private javax.swing.JMenu jMConsultas;
    private javax.swing.JMenu jMMateria;
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
